gnodeb:
  controlif:
    ip: "127.0.0.1"
    port: 9487
  dataif:
    ip: "10.200.200.2"
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "93"
    tac: "000001"
    gnbid: "000001"
  slicesupportlist:
    sst: "01"
    sd: "010203"
  test: "test-normal-registration"

ue:
  msin: "00000001"
  key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
  opc: "E8ED289DEBA952E4283B54E88E6183CA"
  amf: "8000"
  sqn: "0000000"
  dnn: "internet"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai:
    sst: 01
    sd: "010203"
  integrity:
    nia0: false
    nia1: false
    nia2: true
  ciphering:
    nea0: true
    nea1: false
    nea2: false
  test: "test-invalid-flows"

amfif:
  ip: "127.0.0.1"
  port: 38412
  name: "free5gc"
